/** Swagger-verified Cairo Bags V1 API paths (no base URL). */
export const ENDPOINTS = {
  account: {
    me: "/api/Account/Me",
    register: "/api/Account/register",
    login: "/api/Account/LogIn",
    logout: "/api/Account/LogOut",
    refreshToken: "/api/Account/refresh-token",
    createAdmin: "/api/Account/create-admin",
    updateUsername: "/api/Account/update-username",
    forgotPasswordRequestCode: "/api/Account/forgot-password/request-code",
    forgotPasswordComplete: "/api/Account/forgot-password/complete",
    changePassword: "/api/Account/change-password",
    setPassword: "/api/Account/set-password",
    markFirstLoginDone: "/api/Account/mark-first-login-done",
  },
  file: {
    upload: "/api/File/Upload",
  },
  translate: {
    text: "/api/translate",
  },
  categories: {
    list: "/api/categories",
    tree: "/api/categories/tree",
    byId: (id) => `/api/categories/${id}`,
    adminCreate: "/api/admin/categories",
    adminUpdate: (id) => `/api/admin/categories/${id}`,
    adminDelete: (id) => `/api/admin/categories/${id}`,
  },
  products: {
    list: "/api/products",
    filterOptions: "/api/products/filter-options",
    featured: "/api/products/featured",
    newArrivals: "/api/products/new-arrivals",
    search: "/api/products/search",
    byId: (id) => `/api/products/${id}`,
    adminCreate: "/api/admin/products",
    adminUpdate: (id) => `/api/admin/products/${id}`,
    adminDelete: (id) => `/api/admin/products/${id}`,
    images: (productId) => `/api/products/${productId}/images`,
    adminUploadImage: (productId) => `/api/admin/products/${productId}/images`,
    adminUploadVariantImage: (productId, variantId) =>
      `/api/admin/products/${productId}/images/variant/${variantId}`,
    adminSetPrimary: (productId, imageId) =>
      `/api/admin/products/${productId}/images/${imageId}/primary`,
    adminReorderImages: (productId) => `/api/admin/products/${productId}/images/reorder`,
    adminDeleteImage: (productId, imageId) =>
      `/api/admin/products/${productId}/images/${imageId}`,
  },
  inventory: {
    status: (variantId) => `/api/inventory/${variantId}/status`,
    adminList: "/api/admin/inventory",
    adminLowStock: "/api/admin/inventory/low-stock",
    adminByVariant: (variantId) => `/api/admin/inventory/${variantId}`,
    adminMovements: (variantId) => `/api/admin/inventory/${variantId}/movements`,
    adminAdjust: (variantId) => `/api/admin/inventory/${variantId}/adjust`,
    adminReserve: (variantId) => `/api/admin/inventory/${variantId}/reserve`,
    adminRelease: (variantId) => `/api/admin/inventory/${variantId}/release`,
  },
  cart: {
    get: "/api/cart",
    addItem: "/api/cart/items",
    updateItem: (variantId) => `/api/cart/items/${variantId}`,
    removeItem: (variantId) => `/api/cart/items/${variantId}`,
    clear: "/api/cart",
    merge: "/api/cart/merge",
  },
  checkout: {
    create: "/api/checkout",
  },
  coupons: {
    validate: "/api/coupons/validate",
  },
  adminCoupons: {
    stats: "/api/admin/coupons/stats",
    list: "/api/admin/coupons",
    byId: (id) => `/api/admin/coupons/${id}`,
    usage: (id) => `/api/admin/coupons/${id}/usage`,
    create: "/api/admin/coupons",
    update: (id) => `/api/admin/coupons/${id}`,
    delete: (id) => `/api/admin/coupons/${id}`,
    activate: (id) => `/api/admin/coupons/${id}/activate`,
    deactivate: (id) => `/api/admin/coupons/${id}/deactivate`,
    duplicate: (id) => `/api/admin/coupons/${id}/duplicate`,
  },
  shippingAddresses: {
    list: "/api/shipping-addresses",
    create: "/api/shipping-addresses",
  },
  orders: {
    list: "/api/orders",
    byId: (id) => `/api/orders/${id}`,
    cancel: (id) => `/api/orders/${id}/cancel`,
  },
  adminOrders: {
    list: "/api/admin/orders",
    byId: (id) => `/api/admin/orders/${id}`,
    processing: (id) => `/api/admin/orders/${id}/processing`,
    shipped: (id) => `/api/admin/orders/${id}/shipped`,
    delivered: (id) => `/api/admin/orders/${id}/delivered`,
    cancel: (id) => `/api/admin/orders/${id}/cancel`,
    refund: (id) => `/api/admin/orders/${id}/refund`,
  },
  payments: {
    proof: (orderId) => `/api/payments/${orderId}/proof`,
    byOrder: (orderId) => `/api/payments/${orderId}`,
  },
  adminPayments: {
    pending: "/api/admin/payments/pending",
    byId: (paymentId) => `/api/admin/payments/${paymentId}`,
    approve: (paymentId) => `/api/admin/payments/${paymentId}/approve`,
    reject: (paymentId) => `/api/admin/payments/${paymentId}/reject`,
  },
  recommendations: {
    trending: "/api/recommendations/trending",
    recentlyViewed: "/api/recommendations/recently-viewed",
    similar: (productId) => `/api/recommendations/similar/${productId}`,
    frequentlyBoughtTogether: (productId) =>
      `/api/recommendations/frequently-bought-together/${productId}`,
  },
  notifications: {
    list: "/api/Notifications",
    unreadCount: "/api/Notifications/unread-count",
    markRead: (id) => `/api/Notifications/read/${id}`,
    markAllRead: "/api/Notifications/read-all",
  },
  systemSettings: {
    get: "/api/SystemSettings",
    update: "/api/SystemSettings",
  },
  signalR: {
    notifications: "/hubs/notifications",
    catalog: "/hubs/catalog",
    statistics: "/hubs/statistics",
  },
  wishlist: {
    list: "/api/wishlist",
    toggle: (productId) => `/api/wishlist/${productId}`,
    remove: (productId) => `/api/wishlist/${productId}`,
    count: "/api/wishlist/count",
  },
  reviews: {
    byProduct: (productId) => `/api/products/${productId}/reviews`,
    summary: (productId) => `/api/products/${productId}/reviews/summary`,
    create: (productId) => `/api/products/${productId}/reviews`,
    update: (id) => `/api/reviews/${id}`,
    delete: (id) => `/api/reviews/${id}`,
    helpful: (id) => `/api/reviews/${id}/helpful`,
    adminDelete: (id) => `/api/admin/reviews/${id}`,
    adminVisibility: (id) => `/api/admin/reviews/${id}/visibility`,
    adminLatest: "/api/admin/reviews/latest",
  },
  newsletter: {
    subscribe: "/api/newsletter/subscribe",
    unsubscribe: "/api/newsletter/unsubscribe",
    me: "/api/newsletter/me",
  },
  adminNewsletter: {
    stats: "/api/admin/newsletter/stats",
    list: "/api/admin/newsletter/subscribers",
    exportCsv: "/api/admin/newsletter/export/csv",
    exportExcel: "/api/admin/newsletter/export/excel",
  },
  home: {
    statistics: "/api/home/statistics",
  },
};
