export const PAYMENT_METHOD = {
  CASH_ON_DELIVERY: 1,
  INSTA_PAY: 2,
  VODAFONE_CASH: 3,
  ORANGE_CASH: 4,
  ETISALAT_CASH: 5,
  WE_PAY: 6,
};

export const PAYMENT_METHOD_LABELS = {
  [PAYMENT_METHOD.CASH_ON_DELIVERY]: "CashOnDelivery",
  [PAYMENT_METHOD.INSTA_PAY]: "InstaPay",
  [PAYMENT_METHOD.VODAFONE_CASH]: "VodafoneCash",
  [PAYMENT_METHOD.ORANGE_CASH]: "OrangeCash",
  [PAYMENT_METHOD.ETISALAT_CASH]: "EtisalatCash",
  [PAYMENT_METHOD.WE_PAY]: "WEPay",
};
